import {
  Blocks,
  Bot,
  BrainCircuit,
  Bug,
  ChartNoAxesColumn,
  Cloud,
  Cpu,
  Database,
  Gamepad2,
  Layers,
  Layout,
  LineChart,
  Lock,
  Palette,
  Server,
  ShieldCheck,
  Smartphone,
  Activity,
  Boxes,
  Glasses,
  Briefcase,
  Compass,
  type LucideIcon,
} from "lucide-react";

const map: { match: RegExp; icon: LucideIcon }[] = [
  { match: /frontend|front-end/i, icon: Layout },
  { match: /backend|back-end/i, icon: Server },
  { match: /full.?stack/i, icon: Layers },
  { match: /mobile/i, icon: Smartphone },
  { match: /game/i, icon: Gamepad2 },
  { match: /data analyst/i, icon: ChartNoAxesColumn },
  { match: /data scientist/i, icon: LineChart },
  { match: /machine learning/i, icon: BrainCircuit },
  { match: /ai engineer|artificial/i, icon: Bot },
  { match: /data engineer/i, icon: Database },
  { match: /devops/i, icon: Boxes },
  { match: /cloud/i, icon: Cloud },
  { match: /reliability|sre/i, icon: Activity },
  { match: /database/i, icon: Database },
  { match: /cyber|security analyst/i, icon: ShieldCheck },
  { match: /penetration|hacker/i, icon: Lock },
  { match: /qa|test/i, icon: Bug },
  { match: /product manager/i, icon: Briefcase },
  { match: /business analyst/i, icon: ChartNoAxesColumn },
  { match: /blockchain/i, icon: Blocks },
  { match: /ar\/vr|augmented|virtual/i, icon: Glasses },
  { match: /embedded/i, icon: Cpu },
  { match: /ui\/ux|design/i, icon: Palette },
];

export function careerIcon(name: string): LucideIcon {
  return map.find((m) => m.match.test(name))?.icon ?? Compass;
}